on: [push]

name: SyncToTemplateSpec

env:
  AZURE_RESOURCE_GROUP: template-specs-uks
  AZURE_TEMPLATE_NAME: deploy-storage
  AZURE_LOCATION: uksouth

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Incremember Major Semver
        id: increment-semver-major
        uses: Benbentwo/increment-semver@master
        with:
          version-level: '-M'

      - name: Update Template Spec
        uses: azure/cli@v1
        with:
          azcliversion: latest
          inlineScript: |
            az ts create --name ${{ env.AZURE_TEMPLATE_NAME }} --version ${{ steps.increment-semver-major.outputs.version }} --location ${{ env.AZURE_LOCATION }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --template-file $GITHUB_WORKSPACE/${{ env.AZURE_TEMPLATE_NAME }}.json        